name: Deploy Worker

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: ./packages/tgimg-worker
        env:
          npm_config_user_agent: pnpm
